name: Python Checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Run Python linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint ruff black bandit pytype

      - name: Run Pylint
        run: |
          pylint **/*.py || exit_code=$?
          exit ${exit_code:-0}

      - name: Run Ruff
        run: |
          ruff check . || exit_code=$?
          exit ${exit_code:-0}

      - name: Run Black (Check only)
        run: |
          black --check . || exit_code=$?
          exit ${exit_code:-0}

      - name: Run Bandit
        run: |
          bandit -r . || exit_code=$?
          exit ${exit_code:-0}

      - name: Run Pytype
        run: |
          pytype . || exit_code=$?
          exit ${exit_code:-0}

      - name: Fail if any linter failed
        run: |
          echo "Re-running tools to capture failures"
          set -e
          pylint **/*.py
          ruff check .
          black --check .
          bandit -r .
          pytype .
